FROM debian
ADD debian.list /etc/apt/sources.list.d/
RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p Antieasy.com/img && \
    chmod -R 754 /var/www/Antieasy.com/ && \
    useradd Roma && groupadd Kozlov && usermod -a -G Kozlov Roma && \
    chown -R Roma:Kozlov /var/www/Antieasy.com && \
    sed -i 's@/var/www/html@/var/www/Antieasy.com@g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Roma/g' /etc/nginx/nginx.conf

ADD index.html /var/www/Antieasy.com/
ADD img.jpg /var/www/Antieasy.com/img/
CMD ["nginx", "-g", "daemon off;"]
